<?php

namespace App\Domain\Collaboration\Enums;

enum ProjectEventType: string
{
    case INVITATION_CREATED = 'INVITATION_CREATED';
    case INVITATION_ACCEPTED = 'INVITATION_ACCEPTED';
    case INVITATION_REVOKED = 'INVITATION_REVOKED';
    case INVITATION_RESENT = 'INVITATION_RESENT';
    case MEMBER_REMOVED = 'MEMBER_REMOVED';
    case MEMBER_ROLE_CHANGED = 'MEMBER_ROLE_CHANGED';
    case OWNERSHIP_TRANSFERRED = 'OWNERSHIP_TRANSFERRED';
}
