<x-app-layout>
    <div class="planops-console"><section class="analytics-page" aria-labelledby="analytics-heading">
        <section class="dashboard-panel" aria-labelledby="export-heading"><p class="planops-eyebrow">Portability</p><h2 id="export-heading">Export your facts</h2><p class="dashboard-note">Download recorded work data.</p><div class="project-overview-actions"><a class="planops-button planops-button-secondary" href="{{ route('exports.projects') }}">Projects CSV</a><a class="planops-button planops-button-secondary" href="{{ route('exports.tasks') }}">Tasks CSV</a><a class="planops-button planops-button-secondary" href="{{ route('exports.activity', ['format' => 'csv']) }}">Activity CSV</a><a class="planops-button planops-button-secondary" href="{{ route('exports.activity', ['format' => 'json']) }}">Activity JSON</a></div></section>
        <header class="dashboard-header"><div><p class="planops-eyebrow">Workspace / measurement</p><h1 id="analytics-heading">Analytics</h1><p>Understand throughput and flow from recorded work facts.</p></div></header>
        <x-dashboard.period-selector :selection="$selection" />
        <section class="dashboard-period-banner"><span class="planops-eyebrow">Selected period</span><strong>{{ $snapshot->reportPeriod->label }}</strong><span>Lead and cycle time use median elapsed calendar hours.</span></section>
        <section class="dashboard-kpi-grid" aria-label="Analytics summary"><x-dashboard.kpi-card label="Created" :value="$snapshot->throughput['created']" help="Distinct top-level tasks" /><x-dashboard.kpi-card label="Completed" :value="$snapshot->throughput['completed']" help="First completion in period" /><x-dashboard.kpi-card label="Lead time" :value="$snapshot->leadTimeMedianHours !== null ? $snapshot->leadTimeMedianHours.' h' : '—'" help="Median created to first completion" /><x-dashboard.kpi-card label="Cycle time" :value="$snapshot->cycleTimeMedianHours !== null ? $snapshot->cycleTimeMedianHours.' h' : '—'" help="Median first start to completion" /></section>
        <div class="analytics-grid"><section class="dashboard-panel" aria-labelledby="throughput-heading"><p class="planops-eyebrow">Overview / throughput</p><h2 id="throughput-heading">Throughput</h2><table class="dashboard-data-table"><caption class="sr-only">Throughput metrics</caption><thead><tr><th scope="col">Metric</th><th scope="col">Value</th></tr></thead><tbody>@foreach (['created' => 'Created', 'completed' => 'Completed', 'started' => 'Started', 'reviewed' => 'Reviewed', 'blocked' => 'Blocked', 'reopened' => 'Reopened'] as $key => $label)<tr><th scope="row">{{ $label }}</th><td>{{ $snapshot->throughput[$key] }}</td></tr>@endforeach</tbody></table></section><section class="dashboard-panel" aria-labelledby="status-time-heading"><p class="planops-eyebrow">Workflow</p><h2 id="status-time-heading">Time in status</h2><table class="dashboard-data-table"><caption class="sr-only">Hours reconstructed in each status</caption><thead><tr><th scope="col">Status</th><th scope="col">Hours</th></tr></thead><tbody>@foreach ($snapshot->timeInStatus as $status => $hours)<tr><th scope="row">{{ str($status)->replace('_', ' ')->title() }}</th><td>{{ number_format($hours, 1) }}</td></tr>@endforeach</tbody></table></section></div>
        <section class="dashboard-panel" aria-labelledby="project-contribution-heading"><p class="planops-eyebrow">Projects</p><h2 id="project-contribution-heading">Project contribution</h2>@if ($snapshot->projectContribution->isEmpty())<p class="dashboard-empty">No eligible project tasks are available for this view.</p>@else<table class="dashboard-data-table"><caption class="sr-only">Project progress contribution</caption><thead><tr><th scope="col">Project</th><th scope="col">Completed</th><th scope="col">Eligible</th><th scope="col">Progress</th></tr></thead><tbody>@foreach ($snapshot->projectContribution as $row)<tr><th scope="row">{{ $row['project'] }}</th><td>{{ $row['completed'] }}</td><td>{{ $row['eligible'] }}</td><td>{{ $row['progress'] }}%</td></tr>@endforeach</tbody></table>@endif</section>
        @if ($snapshot->leadTimeMedianHours === null)<p class="dashboard-note">Not enough completed tasks in this period to calculate cycle time.</p>@endif
    </section></div>
</x-app-layout>
