<x-app-layout>
    <div class="planops-console"><section class="analytics-page" aria-labelledby="project-analytics-heading">
        <header class="dashboard-header"><div><p class="planops-eyebrow">Project / measurement</p><h1 id="project-analytics-heading">{{ $project->name }} analytics</h1><p>{{ $project->key }} · Recorded work movement for this project.</p></div><a href="{{ route('projects.show', $project) }}" class="planops-button planops-button-secondary">Project overview</a></header>
        <x-dashboard.period-selector :selection="$selection" />
        <section class="dashboard-period-banner"><span class="planops-eyebrow">Selected period</span><strong>{{ $snapshot->reportPeriod->label }}</strong></section>
        <section class="dashboard-kpi-grid" aria-label="Project analytics summary"><x-dashboard.kpi-card label="Created" :value="$snapshot->throughput['created']" help="Top-level tasks" /><x-dashboard.kpi-card label="Completed" :value="$snapshot->throughput['completed']" help="First completion in period" /><x-dashboard.kpi-card label="Lead time" :value="$snapshot->leadTimeMedianHours !== null ? $snapshot->leadTimeMedianHours.' h' : '—'" help="Median calendar hours" /><x-dashboard.kpi-card label="Reopened" :value="$snapshot->throughput['reopened']" help="Terminal to active transitions" /></section>
        <section class="dashboard-panel" aria-labelledby="project-throughput-heading"><p class="planops-eyebrow">Project throughput</p><h2 id="project-throughput-heading">Movement by event</h2><table class="dashboard-data-table"><caption class="sr-only">Project throughput metrics</caption><thead><tr><th scope="col">Event</th><th scope="col">Tasks</th></tr></thead><tbody>@foreach (['created' => 'Created', 'completed' => 'Completed', 'started' => 'Started', 'reviewed' => 'Reviewed', 'blocked' => 'Blocked', 'reopened' => 'Reopened'] as $key => $label)<tr><th scope="row">{{ $label }}</th><td>{{ $snapshot->throughput[$key] }}</td></tr>@endforeach</tbody></table></section>
    </section></div>
</x-app-layout>
