<x-app-layout>
    <div class="planops-console"><section class="dashboard-page" aria-labelledby="dashboard-heading">
        <header class="dashboard-header"><div><p class="planops-eyebrow">Workspace / signal</p><h1 id="dashboard-heading">Dashboard</h1><p>Current work at a glance, with activity measured for the selected period.</p></div><a href="{{ route('my-work') }}" class="planops-button planops-button-secondary">Open My Work</a></header>
        <x-dashboard.period-selector :selection="$selection" />
        <section class="dashboard-period-banner" aria-label="Selected period"><span class="planops-eyebrow">Reporting period</span><strong>{{ $snapshot->reportPeriod->label }}</strong><span>All timestamps are interpreted in your configured timezone.</span></section>
        <section class="dashboard-kpi-grid" aria-label="Current state metrics"><x-dashboard.kpi-card label="Active Projects" :value="$snapshot->activeProjects" help="Not archived, completed, or cancelled" /><x-dashboard.kpi-card label="In Progress" :value="$snapshot->statusCounts['IN_PROGRESS']" help="Current top-level tasks" /><x-dashboard.kpi-card label="In Review" :value="$snapshot->statusCounts['IN_REVIEW']" help="Current top-level tasks" /><x-dashboard.kpi-card label="Overdue" :value="$snapshot->overdueCount" help="Open tasks past their due date" /></section>
        <div class="dashboard-content-grid">
            <section class="dashboard-panel" aria-labelledby="throughput-heading"><div class="dashboard-panel-heading"><div><p class="planops-eyebrow">Tracked Work Activity</p><h2 id="throughput-heading">Period movement</h2></div><span>{{ $snapshot->reportPeriod->label }}</span></div><div class="dashboard-throughput-grid"><div><strong>{{ $snapshot->period['created'] }}</strong><span>Created</span></div><div><strong>{{ $snapshot->period['completed'] }}</strong><span>Completed</span></div><div><strong>{{ $snapshot->period['balance'] }}</strong><span>Balance</span></div></div><table class="dashboard-data-table"><caption class="sr-only">Period movement values</caption><thead><tr><th scope="col">Metric</th><th scope="col">Value</th><th scope="col">Definition</th></tr></thead><tbody><tr><th scope="row">Created</th><td>{{ $snapshot->period['created'] }}</td><td>Distinct top-level task creation events</td></tr><tr><th scope="row">Completed</th><td>{{ $snapshot->period['completed'] }}</td><td>Distinct top-level completion events</td></tr><tr><th scope="row">Balance</th><td>{{ $snapshot->period['balance'] }}</td><td>Created minus completed</td></tr></tbody></table></section>
            <section class="dashboard-panel" aria-labelledby="status-heading"><p class="planops-eyebrow">Current state</p><h2 id="status-heading">Status distribution</h2><table class="dashboard-data-table"><caption class="sr-only">Current top-level task status distribution</caption><thead><tr><th scope="col">Status</th><th scope="col">Tasks</th></tr></thead><tbody>@foreach (['BACKLOG' => 'Backlog', 'NOT_STARTED' => 'Not started', 'IN_PROGRESS' => 'In progress', 'IN_REVIEW' => 'In review', 'BLOCKED' => 'Blocked', 'DONE' => 'Done'] as $status => $label)<tr><th scope="row">{{ $label }}</th><td>{{ $snapshot->statusCounts[$status] }}</td></tr>@endforeach</tbody></table><p class="dashboard-note">Cancelled tasks are excluded. Subtasks do not add weight.</p></section>
        </div>
        <section class="dashboard-panel" aria-labelledby="activity-heading"><div class="dashboard-panel-heading"><div><p class="planops-eyebrow">Recent events</p><h2 id="activity-heading">Activity in this period</h2></div><a href="{{ route('activity') }}">View full activity</a></div>@if ($snapshot->recentActivity->isEmpty())<p class="dashboard-empty">No tracked activity was recorded in this period.</p>@else<ul class="dashboard-activity-list">@foreach ($snapshot->recentActivity as $activity)<li><strong>{{ str($activity->event_type->value)->replace('_', ' ')->title() }}</strong><span>{{ $activity->task?->title ?? 'Historical task' }}</span><time datetime="{{ $activity->created_at?->toIso8601String() }}">{{ $activity->created_at?->format('M j, Y · H:i') }}</time></li>@endforeach</ul>@endif</section>
    </section></div>
</x-app-layout>
